### ISSUE TITLE
About the datasets

### ISSUE THREAD

**Issue by zztzzt200** [huzexi/SADenseNet#1]
Thank you for your great work!
     The page you shared with generated HDF5 files has expired， Could you please update the page?

**Comment by huzexi** [comment]
@zztzzt200 Hi, thanks for your attention to my work.
[The link](https://unisydneyedu-my.sharepoint.com/:f:/g/personal/zehu6197_uni_sydney_edu_au/Ej2faHBEGV9BtGbOpZuBZV4BKh34A2IoR9nQVbArXs4SDw?e=LsvWip) has been updated with the new expiry date.

As the cloud storage is provided by my university (The University of Sydney), it will expire after one year and needs manual renewal. Therefore, I would encourage readers to download the datasets from the original sources and generate HDF5 files with the provided script. In spite of that, you are welcome to use the pre-computed HDF5 files or remind me to renew it again if expiration happens again.
